server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/User?createDatabaseIfNotExist=true
    username: root
    password: janiru849
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true